# Generated by Django 2.2 on 2019-05-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('summary', models.CharField(max_length=2000)),
                ('releaseDate', models.DateField()),
                ('borrowStatus', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BorrowBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowBy', models.CharField(max_length=50)),
                ('borrowDate', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('returnDate', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Books')),
            ],
            options={
                'verbose_name': 'BorrowBooks',
                'verbose_name_plural': 'BorrowBooks',
                'db_table': 'BorrowBooks',
                'get_latest_by': 'borrowDate',
            },
        ),
    ]
