# Generated by Django 2.2 on 2019-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbooks',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
