# Generated by Django 2.2 on 2019-05-22 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrowbooks_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbooks',
            name='borrowBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
